apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  selector:
    matchLabels:
      app: expense-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: bom.ocir.io/oraclepartnersas/expense-mgmt-img:${BUILDRUN_HASH}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 1521  # Add port 1521 for Oracle database          
---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: oracle
    port: 1521
    targetPort: 1521  # Expose port 1521 for Oracle database
    protocol: TCP
  selector:
    app: expense-tracker
