
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  selector:
    matchLabels:
      app: expense-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
    # enter the path to your image, be sure to include the correct region prefix
        image: expense-tracker:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
    # enter the name of the secret you created
      - name: todolistpullsecret3
---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: expense-tracker

---