on:
  push:
    branches:
      - 'feature/test-github-action-1'

jobs:
  clone-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install OCI CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install oci-cli

      - name: Set up environment variables
        run: |
          echo "OCI_CLI_USER=${{ secrets.OCI_CLI_USER }}" >> $GITHUB_ENV
          echo "OCI_CLI_TENANCY=${{ secrets.OCI_CLI_TENANCY }}" >> $GITHUB_ENV
          echo "OCI_CLI_FINGERPRINT=${{ secrets.OCI_CLI_FINGERPRINT }}" >> $GITHUB_ENV
          echo "OCI_CLI_KEY_CONTENT=${{ secrets.OCI_CLI_KEY_CONTENT }}" >> $GITHUB_ENV
          echo "OCI_CLI_REGION=${{ secrets.OCI_CLI_REGION }}" >> $GITHUB_ENV
          echo "BRANCH_REF=${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo -e "[DEFAULT]\nuser=${{ secrets.OCI_CLI_USER }}\nfingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}\nkey_file=${HOME}/.oci/oci_api_key.pem\ntenancy=${{ secrets.OCI_CLI_TENANCY }}\nregion=${{ secrets.OCI_CLI_REGION }}" > ~/.oci/config
          echo "${{ secrets.OCI_API_KEY_PEM }}" > ${HOME}/.oci/oci_api_key.pem
          chmod 600 ${HOME}/.oci/oci_api_key.pem

      - name: Clone database
        run: |
          chmod +x ./scripts/clone-db.sh
          ./scripts/clone-db.sh ${{ secrets.DB_NAME }} ${{ secrets.NEW_DB_NAME }} ${{ secrets.NEW_DB_COMPARTMENT }} ${{ secrets.DB_TDE_WALLET }}

  setup_users:
    needs: clone-db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up users
        run: |
          # Your commands to set up users go here
          echo "Setting up users..."