on:
  push:
    branches:
      - 'feature/test-github-action-1'

jobs:
  clone-db:
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    env:
      OCI_CLI_USER: ocid1.user.oc1..aaaaaaaajxmzb5c53vppyqqbsfidw6ltgkpitiswxshc37soo3ebw3zxl4xa
      OCI_CLI_TENANCY: ocid1.tenancy.oc1..aaaaaaaafj37mytx22oquorcznlfuh77cd45int7tt7fo27tuejsfqbybzrq
      OCI_CLI_FINGERPRINT: ed:0d:8e:a6:ca:8a:5c:06:cb:f0:99:3a:78:43:db:8f
      OCI_CLI_KEY_CONTENT: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD1Uu2TWhgyB5ph
        OnoNOQy1Mp/qRsrZP8FUD/ZKjZYEHjIv+3EtJ0DyZQny9dQyOLqzf8b2UnP1nxIJ
        AAtBCi475NkWrq1H4/J1a9jL5d3kwcV+g1TxoWqcHtFd0CauHYM+wGe9laCgMTCZ
        HCRLsAfgCXRU8jh3J7jciWjAtMbOfkBd9JYjqW1IfcRRV/TZfo/bJRl+PF5GVN9x
        AlMb4Bn1bx8Chk1NtddsnjRkYBgaJdZoLAHRhXkWmvORJMn/70BqEgxntxH+s0a2
        Kv1ZtziVziaL6Nj+6bCrkFtL9AklBesdCuV4KnL9Thg0KJtGJP0RhLiI48rFFoFM
        VjQk9Oa3AgMBAAECggEBAOsQRuxGC6EEf/xh18kLvQ1yMKB+rKd123z8vnW5LOFN
        PbGUMGGfly+reNkAjA6DJQIRkUc8wje778AH9sCfTKW/JfQB869Kz2uLpvPYkcE7
        mk0a8i2FCW4GaX6GkEmNpdBe9AhIctyLxZEv0edkCGe3J2ytm0UxHoTSdTkQ/t2j
        YynWeR0ZNI/aznPKCcwEmipetilT3lH3xMYqcbixGOqfrAPdS2LE74LO8rp03tjb
        xPBgeiwZ9PyieOZCJ0zZA2BFRAX9imY6Ga43P5bH6X8VwYygrEUzG5PT58l8GSX/
        Ih8xavetRfNSrqV6QBKuitKhK7SMS9S1HYzzRFZ/5cECgYEA/TG823RLSmy7JbIi
        4U+WbLY868at1HZDH1brtkNtv0QsmdKuAJpBylXsTD5Xfw6iO5nTNKIyMnhleaMT
        0BC0Id7T9/8tnuHfkCCSchfEFVIDdjyPHVm4sUe9TEpF2mkddjJQNtU21bPIeZxQ
        O1FYi2c7AKZidALw3iOeZ4/f31kCgYEA+ArdGbj+3YBdBN7/Vsu2DN+RJa14jujI
        Kb7fFq1JmNrfUL8HgsH3DOkK0kaEr+I7IU2+8/nvt/Svl2jcM4SM/qSD7818Wo44
        5akk1w883Ap5++HTP1TE2RLIKtH7ysPU/GZ/3wOmWKZJ4TjSbs7TZp7n5pi/7Djf
        bW+mKpE/xI8CgYEAgIHxF/VjjWe4aP6L442QjKbGLukNK0vG764fPsfkePJyLLSY
        qiehAsAvidcOc6eKwfNmFk3IaoNfBai2kqEXvCUrsrBqiDyeSrmteokDdcrFhQph
        nQT/z8LYmlMMNzmowWfx/JKlHTv9oXOr6R91cHO5p6/LQpSHikfLy0Zj2ykCgYAD
        SAmCxJrCjWctoFGacVl4NCD0caYNpfC39Kl44FP/7K1VoSFVToGZLyAQhhRNS13i
        4+dpzN2p/lewVhfLqq4+1ChWrM4/WHBSQXmWSsJQWucgOO2VgeaUxJXXUy3UkeCo
        ciaw6ZhyxchmbV0DUEMlsWZ5+31Wf64dAYQePgus6wKBgFJ+iaqE76dp/nVKcbbU
        ljRB1XMnA1K8cwZvwqDfnRoKbA8+jsgXQTs7W57z9ktKU2wV4JL0OvNfnwsdOrwk
        r4VCUvfonRg/k/9A6+VRw1xcXqMQ+L2J1MWRadQiXQx7MSjwWGyaRPfURdxzUoi9
        bYDZl5UVuwIj1vr7NB5qM3/g
        -----END PRIVATE KEY-----
      OCI_CLI_REGION: ap-mumbai-1

    steps:
      - name: Check OCI CLI version
        run: oci -v

      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true --query "data[?name==`testing`].id"'


      - name: Retrieve the display name and shape of the instances in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'

      - name: List the display name and shape of the instances in my compartment
        run: |
          echo ${{ steps.find-instances.outputs.output }} | jq .     

      - name: Clone database
        run: |
          chmod +x ./scripts/clone-db.sh
          ./scripts/clone-db.sh ${{ secrets.DB_NAME }} ${{ secrets.NEW_DB_NAME }} ${{ secrets.NEW_DB_COMPARTMENT }} ${{ secrets.DB_TDE_WALLET }}
