on:
  push:
    branches:
      - 'feature/test-github-action-1'
jobs:
  clone-db:
    runs-on: ubuntu-latest
    node-version: '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment variables
        run: |
          echo "OCI_CLI_USER=${{ secrets.OCI_CLI_USER }}" >> $GITHUB_ENV
          echo "OCI_CLI_TENANCY=${{ secrets.OCI_CLI_TENANCY }}" >> $GITHUB_ENV
          echo "OCI_CLI_FINGERPRINT=${{ secrets.OCI_CLI_FINGERPRINT }}" >> $GITHUB_ENV
          echo "OCI_CLI_KEY_CONTENT=${{ secrets.OCI_CLI_KEY_CONTENT }}" >> $GITHUB_ENV
          echo "OCI_CLI_REGION=${{ secrets.OCI_CLI_REGION }}" >> $GITHUB_ENV
          echo "BRANCH_REF=${{ github.event.ref }}" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Clone database
        run: |
          ./../../scripts/clone-db.sh ${{ secrets.DB_NAME }} ${{ secrets.NEW_DB_NAME }} ${{ secrets.NEW_DB_COMPARTMENT }} ${{ secrets.DB_TDE_WALLET }}

  setup_users:
    needs: clone-db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up users
        run: |
          # Your commands to set up users go here
          echo "Setting up users..."