on:
  push:
    branches:
      - 'feature/test-github-action-1'

jobs:
  clone-db:
    environment: webhook-secret
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{secrets.OCI_CLI_FINGERPRINT}}
      OCI_CLI_KEY_CONTENT: ${{secrets.OCI_CLI_KEY_CONTENT}}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - uses: actions/checkout@v2 # Make sure to include this step  

      - name: Set up environment variables
        env :
          a : ${{ secrets.OCI_CLI_USER }}
        run : |
          echo "OCI_CLI_USER: '${{ secrets.OCI_CLI_USER }}'"
          echo "OCI_CLI_FINGERPRINT: '${{ secrets.OCI_CLI_FINGERPRINT }}'" | sed 's/./& /g'
          echo "OCI_CLI_REGION: '${{ secrets.OCI_CLI_REGION }}'" | sed 's/./& /g'
          echo "OCI_CLI_TENANCY: '${{ secrets.OCI_CLI_TENANCY }}'" | sed 's/./& /g'
          echo $a | sed 's/./& /g'


    
      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true --query "data[?name==`labexer`].id"'

      - name: Retrieve the display name and shape of the instances in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'

      - name: List the display name and shape of the instances in my compartment
        run: |
          echo ${{ steps.find-instances.outputs.output }} | jq .  

      - name: Create Kubernetes Configuration
        run: |
          oci ce cluster create-kubeconfig \
            --cluster-id ocid1.cluster.oc1.ap-mumbai-1.aaaaaaaa7dentcobq4z5xpqkn7kdpcg6obon4icgghgwe2fgtckgxg5oew6q \
            --file $HOME/.kube/config \
            --region ap-mumbai-1 \
            --token-version 2.0.0 \
            --kube-endpoint PUBLIC_ENDPOINT

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ocid1.cluster.oc1.ap-mumbai-1.aaaaaaaa7dentcobq4z5xpqkn7kdpcg6obon4icgghgwe2fgtckgxg5oew6q


      - name: Install Oracle Database Operator
        run: |
          kubectl apply -f build_spec_with_operator.yaml --validate=false



      - name: Create Autonomous Database from Clone
        run: |
          # Configuration Variables
          SOURCE_DB_OCID="ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljrobogfhqajjp7nk74dr3bputn3aa646uistr5xiyxwu5tkh3octuq"
          CLONE_TYPE="FULL"
          CLONE_DB_DISPLAY_NAME="Test Clone CICD"
          CLONE_DB_NAME="TestCloneAutomateCICD"
          COMPARTMENT_OCID="ocid1.compartment.oc1..aaaaaaaavkerdgzd55avjsnomocb2ttxb4j4j7gecxwdfwtstwb2iyowtfba"
          ADMIN_PASSWORD="Igdefault@123"
          COMPUTE_MODEL="ECPU"
          COMPUTE_COUNT=2
          DB_WORKLOAD="OLTP"

          # Create Autonomous Database from Clone
          echo "Creating Autonomous Database from Clone..."
          CREATE_RESPONSE=$(oci db autonomous-database create-from-clone \
                              --clone-type "$CLONE_TYPE" \
                              --compartment-id "$COMPARTMENT_OCID" \
                              --source-id "$SOURCE_DB_OCID" \
                              --display-name "$CLONE_DB_DISPLAY_NAME" \
                              --db-name "$CLONE_DB_NAME" \
                              --wait-for-state AVAILABLE \
                              --admin-password "$ADMIN_PASSWORD" \
                              --data-storage-size-in-tbs 1 \
                              --compute-model "$COMPUTE_MODEL" \
                              --compute-count "$COMPUTE_COUNT" \
                              --db-workload "$DB_WORKLOAD")

          if [ -z "$CREATE_RESPONSE" ]; then
              echo "Failed to create the Autonomous Database from Clone."
              exit 1
          else
              CLONED_DB_OCID=$(echo "$CREATE_RESPONSE" | jq -r '.data.id')
              echo "Successfully created the Autonomous Database from Clone. OCID: $CLONED_DB_OCID"
          fi
